use crate::schema::{ParsedSchema, TableDefinition};
use crate::types::TypeMapper;
use anyhow::Result;
use convert_case::{Case, Casing};
use quote::quote;

pub fn generate(schema: &ParsedSchema) -> Result<String> {
    let mut tokens = quote! {
        // Auto-generated query functions - DO NOT EDIT MANUALLY
        // 
        // This file is generated by supabase-rust-gen.
        // Run `supabase-rust-gen --with-queries` to regenerate.
    };

    for table in &schema.tables {
        let query_impl = generate_query_functions(table);
        tokens.extend(query_impl);
    }

    Ok(prettyplease::unparse(&syn::parse2(tokens)?))
}

fn generate_query_functions(table: &TableDefinition) -> proc_macro2::TokenStream {
    let struct_name = syn::Ident::new(
        &TypeMapper::table_to_struct_name(&table.name),
        proc_macro2::Span::call_site(),
    );
    
    let table_name = &table.name;
    
    let select_all_fn = syn::Ident::new(
        &format!("select_all_{}", table.name.to_case(Case::Snake)),
        proc_macro2::Span::call_site(),
    );
    
    let select_eq_fn = syn::Ident::new(
        &format!("select_{}_eq", table.name.to_case(Case::Snake)),
        proc_macro2::Span::call_site(),
    );
    
    let insert_one_fn = syn::Ident::new(
        &format!("insert_one_{}", table.name.to_case(Case::Snake)),
        proc_macro2::Span::call_site(),
    );
    
    let insert_many_fn = syn::Ident::new(
        &format!("insert_many_{}", table.name.to_case(Case::Snake)),
        proc_macro2::Span::call_site(),
    );
    
    let update_fn = syn::Ident::new(
        &format!("update_{}", table.name.to_case(Case::Snake)),
        proc_macro2::Span::call_site(),
    );
    
    let delete_fn = syn::Ident::new(
        &format!("delete_{}", table.name.to_case(Case::Snake)),
        proc_macro2::Span::call_site(),
    );

    quote! {
        impl #struct_name {
            pub async fn #select_all_fn(
                client: &postgrest::Postgrest,
            ) -> Result<Vec<Self>, Box<dyn std::error::Error>> {
                let resp = client
                    .from(#table_name)
                    .select("*")
                    .execute()
                    .await?;
                    
                let text = resp.text().await?;
                let rows: Vec<Self> = serde_json::from_str(&text)?;
                Ok(rows)
            }

            pub async fn #select_eq_fn(
                client: &postgrest::Postgrest,
                column: &str,
                value: &str,
            ) -> Result<Vec<Self>, Box<dyn std::error::Error>> {
                let resp = client
                    .from(#table_name)
                    .select("*")
                    .eq(column, value)
                    .execute()
                    .await?;
                    
                let text = resp.text().await?;
                let rows: Vec<Self> = serde_json::from_str(&text)?;
                Ok(rows)
            }

            pub async fn #insert_one_fn(
                client: &postgrest::Postgrest,
                row: &Self,
            ) -> Result<Vec<Self>, Box<dyn std::error::Error>> {
                let body = serde_json::to_string(&row)?;
                let resp = client
                    .from(#table_name)
                    .insert(body)
                    .execute()
                    .await?;
                    
                let text = resp.text().await?;
                let rows: Vec<Self> = serde_json::from_str(&text)?;
                Ok(rows)
            }

            pub async fn #insert_many_fn(
                client: &postgrest::Postgrest,
                rows: &[Self],
            ) -> Result<Vec<Self>, Box<dyn std::error::Error>> {
                let body = serde_json::to_string(&rows)?;
                let resp = client
                    .from(#table_name)
                    .insert(body)
                    .execute()
                    .await?;
                    
                let text = resp.text().await?;
                let inserted: Vec<Self> = serde_json::from_str(&text)?;
                Ok(inserted)
            }

            /// Update rows in the `#table_name` table
            pub async fn #update_fn(
                client: &postgrest::Postgrest,
                column: &str,
                value: &str,
                updates: &serde_json::Value,
            ) -> Result<Vec<Self>, Box<dyn std::error::Error>> {
                let body = serde_json::to_string(updates)?;
                let resp = client
                    .from(#table_name)
                    .eq(column, value)
                    .update(body)
                    .execute()
                    .await?;
                    
                let text = resp.text().await?;
                let rows: Vec<Self> = serde_json::from_str(&text)?;
                Ok(rows)
            }

            /// Delete rows from the `#table_name` table
            pub async fn #delete_fn(
                client: &postgrest::Postgrest,
                column: &str,
                value: &str,
            ) -> Result<Vec<Self>, Box<dyn std::error::Error>> {
                let resp = client
                    .from(#table_name)
                    .eq(column, value)
                    .delete()
                    .execute()
                    .await?;
                    
                let text = resp.text().await?;
                let rows: Vec<Self> = serde_json::from_str(&text)?;
                Ok(rows)
            }
        }
    }
}