use crate::schema::ParsedSchema;
use anyhow::Result;
use convert_case::{Case, Casing};
use quote::quote;

pub fn generate(schema: &ParsedSchema) -> Result<String> {
    let mut tokens = quote! {
        // Auto-generated RLS helper functions - DO NOT EDIT MANUALLY
        // 
        // This file is generated by supabase-rust-gen.
        // Run `supabase-rust-gen --with-rls` to regenerate.
        // 
        // Note: These are stub functions. Implement actual RLS checks
        // based on your Supabase security policies.
        
        use postgrest::Postgrest;
    };

    for table in &schema.tables {
        let rls_impl = generate_rls_functions(table);
        tokens.extend(rls_impl);
    }

    Ok(prettyplease::unparse(&syn::parse2(tokens)?))
}

fn generate_rls_functions(table: &crate::schema::TableDefinition) -> proc_macro2::TokenStream {
    let table_name = &table.name;
    let struct_name = syn::Ident::new(
        &crate::types::TypeMapper::table_to_struct_name(table_name),
        proc_macro2::Span::call_site(),
    );
    
    let can_select_fn = syn::Ident::new(
        &format!("can_select_{}", table_name.to_case(Case::Snake)),
        proc_macro2::Span::call_site(),
    );
    
    let can_insert_fn = syn::Ident::new(
        &format!("can_insert_{}", table_name.to_case(Case::Snake)),
        proc_macro2::Span::call_site(),
    );
    
    let can_update_fn = syn::Ident::new(
        &format!("can_update_{}", table_name.to_case(Case::Snake)),
        proc_macro2::Span::call_site(),
    );
    
    let can_delete_fn = syn::Ident::new(
        &format!("can_delete_{}", table_name.to_case(Case::Snake)),
        proc_macro2::Span::call_site(),
    );

    quote! {
        impl #struct_name {
            /// Check if the current user can SELECT from `#table_name`
            /// 
            /// Implement this based on your RLS policies in Supabase
            pub async fn #can_select_fn(
                client: &Postgrest,
                user_id: Option<&str>,
            ) -> Result<bool, Box<dyn std::error::Error>> {
                // TODO: Implement actual RLS check
                // Example: Check if user has permission to read this table
                Ok(true)
            }

            /// Check if the current user can INSERT into `#table_name`
            pub async fn #can_insert_fn(
                client: &Postgrest,
                user_id: Option<&str>,
                row: &Self,
            ) -> Result<bool, Box<dyn std::error::Error>> {
                // TODO: Implement actual RLS check
                // Example: Check if user can create records
                Ok(true)
            }

            /// Check if the current user can UPDATE rows in `#table_name`
            pub async fn #can_update_fn(
                client: &Postgrest,
                user_id: Option<&str>,
                row_id: &str,
            ) -> Result<bool, Box<dyn std::error::Error>> {
                // TODO: Implement actual RLS check
                // Example: Check if user owns the record
                Ok(true)
            }

            /// Check if the current user can DELETE from `#table_name`
            pub async fn #can_delete_fn(
                client: &Postgrest,
                user_id: Option<&str>,
                row_id: &str,
            ) -> Result<bool, Box<dyn std::error::Error>> {
                // TODO: Implement actual RLS check
                // Example: Check if user has delete permissions
                Ok(true)
            }
        }
    }
}