use crate::schema::{ColumnDefinition, ParsedSchema, TableDefinition};
use crate::types::TypeMapper;
use anyhow::Result;
use quote::quote;

pub fn generate(schema: &ParsedSchema, type_mapper: &TypeMapper) -> Result<String> {
    let mut tokens = quote! {
        // Auto-generated Supabase types - DO NOT EDIT MANUALLY
        // 
        // This file is generated by supabase-rust-gen.
        // Run `supabase-rust-gen` to regenerate.
        
        use serde::{Deserialize, Serialize};
        
        #[cfg(feature = "chrono")]
        use chrono;
        
        #[cfg(feature = "uuid")]
        use uuid::Uuid;
    };

    for table in &schema.tables {
        let struct_def = generate_struct(table, type_mapper);
        tokens.extend(struct_def);
    }

    Ok(prettyplease::unparse(&syn::parse2(tokens)?))
}

fn generate_struct(table: &TableDefinition, type_mapper: &TypeMapper) -> proc_macro2::TokenStream {
    let struct_name = syn::Ident::new(
        &TypeMapper::table_to_struct_name(&table.name),
        proc_macro2::Span::call_site(),
    );

    let fields: Vec<_> = table
        .columns
        .iter()
        .map(|col| generate_field(col, type_mapper))
        .collect();

    let doc = format!("Row from the `{}` table", table.name);

    quote! {
        #[doc = #doc]
        #[derive(Debug, Clone, Serialize, Deserialize)]
        #[serde(rename_all = "camelCase")]
        pub struct #struct_name {
            #(#fields),*
        }
    }
}

fn generate_field(col: &ColumnDefinition, type_mapper: &TypeMapper) -> proc_macro2::TokenStream {
    let field_name = syn::Ident::new(&col.name, proc_macro2::Span::call_site());
    let rust_type: syn::Type = syn::parse_str(&type_mapper.map_column(col))
        .expect("Failed to parse type");
    
    let mut tokens = quote! {
        pub #field_name: #rust_type
    };

    if let Some(desc) = &col.description {
        let doc = format!(" {}", desc);
        tokens = quote! {
            #[doc = #doc]
            #tokens
        };
    }

    // Add serde skip_serializing_if for Option types
    if col.is_nullable {
        let field_name_str = col.name.to_string();
        tokens = quote! {
            #[serde(skip_serializing_if = "Option::is_none")]
            #tokens
        };
    }

    tokens
}